services:
  combination-server:
    build:
      context: .
      dockerfile: ./build/combination/Dockerfile
    container_name: combination-server
    restart: always
    environment:
      - ENV=${ENV}
      - PORT=${SERVER_CONTAINER_PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_CONTAINER_PORT}
      - DB_SSL_MODE=${DB_SSL_MODE}
    depends_on:
      combination-db:
        condition: service_healthy
    ports:
      - "${SERVER_HOST_PORT}:${SERVER_CONTAINER_PORT}"
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=localhost:${SERVER_CONTAINER_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  combination-db:
    image: postgres:17
    container_name: combination-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_HOST_PORT}:${DB_CONTAINER_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - combination-db-data:/var/lib/postgresql/data

  combination-grpc-gateway:
    build:
      context: .
      dockerfile: ./build/gateway/Dockerfile
    container_name: combination-grpc-gateway
    restart: always
    environment:
      - ENV=${ENV}
      - PORT=${GRPC_GATEWAY_CONTAINER_PORT}
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_CONTAINER_PORT}
    ports:
      - "${GRPC_GATEWAY_HOST_PORT}:${GRPC_GATEWAY_CONTAINER_PORT}"

volumes:
  combination-db-data: